@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.yor42.projectazure.gameobject.blocks;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;